# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'docgen_main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(452, 316)
        main_window.setMinimumSize(QtCore.QSize(452, 316))
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vertical_layout = QtWidgets.QVBoxLayout()
        self.vertical_layout.setObjectName("vertical_layout")
        self.input_sct = QtWidgets.QGroupBox(self.central_widget)
        self.input_sct.setMinimumSize(QtCore.QSize(0, 50))
        self.input_sct.setObjectName("input_sct")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.input_sct)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.input_file_lbl = QtWidgets.QLabel(self.input_sct)
        self.input_file_lbl.setObjectName("input_file_lbl")
        self.horizontalLayout_2.addWidget(self.input_file_lbl)
        self.input_file_txt = QtWidgets.QLineEdit(self.input_sct)
        self.input_file_txt.setEnabled(False)
        self.input_file_txt.setObjectName("input_file_txt")
        self.horizontalLayout_2.addWidget(self.input_file_txt)
        self.input_file_btn = QtWidgets.QPushButton(self.input_sct)
        self.input_file_btn.setObjectName("input_file_btn")
        self.horizontalLayout_2.addWidget(self.input_file_btn)
        self.vertical_layout.addWidget(self.input_sct)
        self.output_sct = QtWidgets.QGroupBox(self.central_widget)
        self.output_sct.setObjectName("output_sct")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.output_sct)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.output_dir_lbl = QtWidgets.QLabel(self.output_sct)
        self.output_dir_lbl.setObjectName("output_dir_lbl")
        self.horizontalLayout_3.addWidget(self.output_dir_lbl)
        self.output_dir_txt = QtWidgets.QLineEdit(self.output_sct)
        self.output_dir_txt.setEnabled(False)
        self.output_dir_txt.setObjectName("output_dir_txt")
        self.horizontalLayout_3.addWidget(self.output_dir_txt)
        self.output_dir_btn = QtWidgets.QPushButton(self.output_sct)
        self.output_dir_btn.setObjectName("output_dir_btn")
        self.horizontalLayout_3.addWidget(self.output_dir_btn)
        self.vertical_layout.addWidget(self.output_sct)
        self.options_sct = QtWidgets.QGroupBox(self.central_widget)
        self.options_sct.setMinimumSize(QtCore.QSize(0, 50))
        self.options_sct.setObjectName("options_sct")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.options_sct)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.send_docs_cbx = QtWidgets.QCheckBox(self.options_sct)
        self.send_docs_cbx.setObjectName("send_docs_cbx")
        self.verticalLayout_3.addWidget(self.send_docs_cbx)
        self.print_docs_cbx = QtWidgets.QCheckBox(self.options_sct)
        self.print_docs_cbx.setObjectName("print_docs_cbx")
        self.verticalLayout_3.addWidget(self.print_docs_cbx)
        self.vertical_layout.addWidget(self.options_sct)
        self.generation_pbr = QtWidgets.QProgressBar(self.central_widget)
        self.generation_pbr.setProperty("value", 24)
        self.generation_pbr.setObjectName("generation_pbr")
        self.vertical_layout.addWidget(self.generation_pbr)
        self.generate_sct = QtWidgets.QHBoxLayout()
        self.generate_sct.setObjectName("generate_sct")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.generate_sct.addItem(spacerItem)
        self.cancel_btn = QtWidgets.QPushButton(self.central_widget)
        self.cancel_btn.setEnabled(False)
        self.cancel_btn.setObjectName("cancel_btn")
        self.generate_sct.addWidget(self.cancel_btn)
        self.generate_btn = QtWidgets.QPushButton(self.central_widget)
        self.generate_btn.setObjectName("generate_btn")
        self.generate_sct.addWidget(self.generate_btn)
        self.vertical_layout.addLayout(self.generate_sct)
        self.verticalLayout_2.addLayout(self.vertical_layout)
        main_window.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(main_window)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 452, 21))
        self.menu_bar.setObjectName("menu_bar")
        self.file_mnu = QtWidgets.QMenu(self.menu_bar)
        self.file_mnu.setObjectName("file_mnu")
        self.source_mnu = QtWidgets.QMenu(self.menu_bar)
        self.source_mnu.setObjectName("source_mnu")
        self.options_mnu = QtWidgets.QMenu(self.menu_bar)
        self.options_mnu.setObjectName("options_mnu")
        self.help_mnu = QtWidgets.QMenu(self.menu_bar)
        self.help_mnu.setObjectName("help_mnu")
        main_window.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(main_window)
        self.status_bar.setObjectName("status_bar")
        main_window.setStatusBar(self.status_bar)
        self.quit_act = QtWidgets.QAction(main_window)
        self.quit_act.setObjectName("quit_act")
        self.excel_act = QtWidgets.QAction(main_window)
        self.excel_act.setObjectName("excel_act")
        self.gsheets_act = QtWidgets.QAction(main_window)
        self.gsheets_act.setObjectName("gsheets_act")
        self.dropbox_act = QtWidgets.QAction(main_window)
        self.dropbox_act.setObjectName("dropbox_act")
        self.mysql_act = QtWidgets.QAction(main_window)
        self.mysql_act.setObjectName("mysql_act")
        self.csv_act = QtWidgets.QAction(main_window)
        self.csv_act.setObjectName("csv_act")
        self.more_act = QtWidgets.QAction(main_window)
        self.more_act.setObjectName("more_act")
        self.updates_act = QtWidgets.QAction(main_window)
        self.updates_act.setObjectName("updates_act")
        self.preferences_act = QtWidgets.QAction(main_window)
        self.preferences_act.setObjectName("preferences_act")
        self.file_mnu.addAction(self.quit_act)
        self.source_mnu.addAction(self.excel_act)
        self.source_mnu.addAction(self.gsheets_act)
        self.source_mnu.addAction(self.dropbox_act)
        self.source_mnu.addAction(self.mysql_act)
        self.source_mnu.addAction(self.csv_act)
        self.options_mnu.addAction(self.preferences_act)
        self.help_mnu.addAction(self.more_act)
        self.help_mnu.addSeparator()
        self.help_mnu.addAction(self.updates_act)
        self.menu_bar.addAction(self.file_mnu.menuAction())
        self.menu_bar.addAction(self.source_mnu.menuAction())
        self.menu_bar.addAction(self.options_mnu.menuAction())
        self.menu_bar.addAction(self.help_mnu.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "DocGen"))
        self.input_sct.setTitle(_translate("main_window", "Input"))
        self.input_file_lbl.setText(_translate("main_window", "Excel file"))
        self.input_file_btn.setText(_translate("main_window", "Browse..."))
        self.output_sct.setTitle(_translate("main_window", "Output"))
        self.output_dir_lbl.setText(_translate("main_window", "Output directory"))
        self.output_dir_btn.setText(_translate("main_window", "Browse..."))
        self.options_sct.setTitle(_translate("main_window", "Options"))
        self.send_docs_cbx.setText(_translate("main_window", "Send documents by email"))
        self.print_docs_cbx.setText(_translate("main_window", "Print documents (default printer)"))
        self.cancel_btn.setText(_translate("main_window", "Cancel"))
        self.generate_btn.setText(_translate("main_window", "Generate"))
        self.file_mnu.setTitle(_translate("main_window", "File"))
        self.source_mnu.setTitle(_translate("main_window", "Source"))
        self.options_mnu.setTitle(_translate("main_window", "Options"))
        self.help_mnu.setTitle(_translate("main_window", "Help"))
        self.quit_act.setText(_translate("main_window", "Quit"))
        self.quit_act.setShortcut(_translate("main_window", "Ctrl+Q"))
        self.excel_act.setText(_translate("main_window", "Excel"))
        self.gsheets_act.setText(_translate("main_window", "Google Sheets"))
        self.dropbox_act.setText(_translate("main_window", "Dropbox"))
        self.mysql_act.setText(_translate("main_window", "MySQL"))
        self.csv_act.setText(_translate("main_window", "CSV"))
        self.more_act.setText(_translate("main_window", "About..."))
        self.updates_act.setText(_translate("main_window", "Check for Updates"))
        self.preferences_act.setText(_translate("main_window", "Preferences"))

