# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_preferences(object):
    def setupUi(self, preferences):
        preferences.setObjectName("preferences")
        preferences.setWindowModality(QtCore.Qt.ApplicationModal)
        preferences.resize(456, 169)
        preferences.setMinimumSize(QtCore.QSize(456, 169))
        preferences.setMaximumSize(QtCore.QSize(456, 169))
        preferences.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(preferences)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vertical_layout = QtWidgets.QVBoxLayout()
        self.vertical_layout.setObjectName("vertical_layout")
        self.email_config_sct = QtWidgets.QGroupBox(preferences)
        self.email_config_sct.setMinimumSize(QtCore.QSize(0, 50))
        self.email_config_sct.setObjectName("email_config_sct")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.email_config_sct)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.email_add_sct = QtWidgets.QHBoxLayout()
        self.email_add_sct.setObjectName("email_add_sct")
        self.add_lbl = QtWidgets.QLabel(self.email_config_sct)
        self.add_lbl.setObjectName("add_lbl")
        self.email_add_sct.addWidget(self.add_lbl)
        self.add_txt = QtWidgets.QLineEdit(self.email_config_sct)
        self.add_txt.setObjectName("add_txt")
        self.email_add_sct.addWidget(self.add_txt)
        self.gmail_lbl = QtWidgets.QLabel(self.email_config_sct)
        self.gmail_lbl.setObjectName("gmail_lbl")
        self.email_add_sct.addWidget(self.gmail_lbl)
        self.verticalLayout_3.addLayout(self.email_add_sct)
        self.email_pass_sct = QtWidgets.QHBoxLayout()
        self.email_pass_sct.setObjectName("email_pass_sct")
        self.pass_lbl = QtWidgets.QLabel(self.email_config_sct)
        self.pass_lbl.setObjectName("pass_lbl")
        self.email_pass_sct.addWidget(self.pass_lbl)
        self.pass_txt = QtWidgets.QLineEdit(self.email_config_sct)
        self.pass_txt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_txt.setObjectName("pass_txt")
        self.email_pass_sct.addWidget(self.pass_txt)
        self.verticalLayout_3.addLayout(self.email_pass_sct)
        self.validate_sct = QtWidgets.QHBoxLayout()
        self.validate_sct.setObjectName("validate_sct")
        self.valid_lbl = QtWidgets.QLabel(self.email_config_sct)
        self.valid_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.valid_lbl.setObjectName("valid_lbl")
        self.validate_sct.addWidget(self.valid_lbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.validate_sct.addItem(spacerItem)
        self.clear_btn = QtWidgets.QPushButton(self.email_config_sct)
        self.clear_btn.setObjectName("clear_btn")
        self.validate_sct.addWidget(self.clear_btn)
        self.validate_btn = QtWidgets.QPushButton(self.email_config_sct)
        self.validate_btn.setObjectName("validate_btn")
        self.validate_sct.addWidget(self.validate_btn)
        self.verticalLayout_3.addLayout(self.validate_sct)
        self.vertical_layout.addWidget(self.email_config_sct)
        self.buttons_sct = QtWidgets.QHBoxLayout()
        self.buttons_sct.setObjectName("buttons_sct")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_sct.addItem(spacerItem1)
        self.cancel_btn = QtWidgets.QPushButton(preferences)
        self.cancel_btn.setEnabled(True)
        self.cancel_btn.setObjectName("cancel_btn")
        self.buttons_sct.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(preferences)
        self.save_btn.setEnabled(False)
        self.save_btn.setObjectName("save_btn")
        self.buttons_sct.addWidget(self.save_btn)
        self.vertical_layout.addLayout(self.buttons_sct)
        self.verticalLayout.addLayout(self.vertical_layout)
        self.quit_act = QtWidgets.QAction(preferences)
        self.quit_act.setObjectName("quit_act")
        self.excel_act = QtWidgets.QAction(preferences)
        self.excel_act.setObjectName("excel_act")
        self.gsheets_act = QtWidgets.QAction(preferences)
        self.gsheets_act.setObjectName("gsheets_act")
        self.dropbox_act = QtWidgets.QAction(preferences)
        self.dropbox_act.setObjectName("dropbox_act")
        self.mysql_act = QtWidgets.QAction(preferences)
        self.mysql_act.setObjectName("mysql_act")
        self.csv_act = QtWidgets.QAction(preferences)
        self.csv_act.setObjectName("csv_act")
        self.more_act = QtWidgets.QAction(preferences)
        self.more_act.setObjectName("more_act")
        self.updates_act = QtWidgets.QAction(preferences)
        self.updates_act.setObjectName("updates_act")
        self.preferences_act = QtWidgets.QAction(preferences)
        self.preferences_act.setObjectName("preferences_act")

        self.retranslateUi(preferences)
        QtCore.QMetaObject.connectSlotsByName(preferences)

    def retranslateUi(self, preferences):
        _translate = QtCore.QCoreApplication.translate
        preferences.setWindowTitle(_translate("preferences", "Preferences"))
        self.email_config_sct.setTitle(_translate("preferences", "Email configuration"))
        self.add_lbl.setText(_translate("preferences", "Address"))
        self.gmail_lbl.setText(_translate("preferences", "@gmail.com"))
        self.pass_lbl.setText(_translate("preferences", "Password"))
        self.valid_lbl.setText(_translate("preferences", "Please validate login information before saving"))
        self.clear_btn.setText(_translate("preferences", "Clear"))
        self.validate_btn.setText(_translate("preferences", "Validate"))
        self.cancel_btn.setText(_translate("preferences", "Cancel"))
        self.save_btn.setText(_translate("preferences", "Save"))
        self.quit_act.setText(_translate("preferences", "Quit"))
        self.quit_act.setShortcut(_translate("preferences", "Ctrl+Q"))
        self.excel_act.setText(_translate("preferences", "Excel"))
        self.gsheets_act.setText(_translate("preferences", "Google Sheets"))
        self.dropbox_act.setText(_translate("preferences", "Dropbox"))
        self.mysql_act.setText(_translate("preferences", "MySQL"))
        self.csv_act.setText(_translate("preferences", "CSV"))
        self.more_act.setText(_translate("preferences", "About..."))
        self.updates_act.setText(_translate("preferences", "Check for Updates"))
        self.preferences_act.setText(_translate("preferences", "Preferences"))

